create table
  public.attempts (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    user_id uuid null,
    request jsonb null,
    response jsonb null,
    breach boolean null,
    constraint attempts_pkey primary key (id),
    constraint attempts_user_id_fkey foreign key (user_id) references auth.users (id)
  ) tablespace pg_default;