create table
  public.leak_logs (
    id bigint generated by default as identity,
    account_id uuid not null,
    created_at timestamp with time zone not null default now(),
    user_input text not null,
    completion text null,
    canary_word text null,
    metadata_json json null,
    constraint leak_logs_pkey primary key (id),
    constraint leak_logs_account_id_fkey foreign key (account_id) references accounts (id)
  ) tablespace pg_default;