# .github/workflows/python_tests.yml
name: Python Tests

on:
    push:
      branches:
        - main
    pull_request_target:
      types:
        - opened
        - labeled

jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'okay-to-test') || (github.event_name == 'push')

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        # Check out pull request's HEAD commit instead of the merge commit to
        # work around an issue where wrong a commit is being checked out.
        # For more details, see:
        # https://github.com/actions/checkout/issues/299.
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: make init

    - name: Run tests
      working-directory: python-sdk
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        BILLING_RATE_INT_10K: ${{ secrets.BILLING_RATE_INT_10K }}
        MASTER_API_KEY: ${{ secrets.MASTER_API_KEY }}
        MASTER_CREDIT_AMOUNT: ${{ secrets.MASTER_CREDIT_AMOUNT }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
        PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      run: |
        pytest
